### ISSUE TITLE
Missing Dependencies for Project Setup

### ISSUE THREAD

**Issue by PlakiaM** [mammoth-eu/mammoth-commons#11]
When setting up the development environment for this project, there are some additional dependencies that need to be installed manually.
- pip install pymoo
- pip install plotly
- pip install --upgrade nbformat
- pip install skl2onnx

**Comment by maniospas** [comment]
Dependencies of the notebook are not supposed to be in `requirements.txt` (to be automatically installed) unless the notebook is explicitly converted into a module.
 
Therefore, @arjunroyihrpa I suggest adding these additional installation instructions at the beginning of the notebook demonstrating TC4. In a related note, please at least turn the visualizations into a module too so that we can have a fully working tc4 pipeline that uses all the modules.

P.S. I am setting Swati as the assignee because for some reason Arjun is not an option in the respective menu.
P.P.S. By the way, we have two requirement files right now, and this one is supposed to have all the dependencies of all modules - so it is quite bloaty because it includes `torch` (never bother with the smaller set of requirements - it's just to minimize docker image size upon deployment by providing the mammoth's core).

**Comment by maniospas** [comment]
Pinging for an update @Swati17293 .

**Comment by maniospas** [comment]
Closing the issue due to lack of activity and my understanding that collaboration has progressed past this issue.
