### ISSUE TITLE
[faceX] Adapting faceX for embedding outputs from models (ex: Face Recognition)

### ISSUE THREAD

**Issue by elmokhtar-mohamedmoussa-idnow** [mammoth-eu/mammoth-commons#14]
Hi,

Right now FaceX is perfectly suited for classification models (such as gender classification). FaceX model focus heatmap is based on gradCam, it turns out GradCam can be applicable for embedding models such as face recognition :

[Adapting pixel attribution methods for embedding outputs from models](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Pixel%20Attribution%20for%20embeddings.ipynb)

I think FaceX can be adapted to face recognition using the tutorial above, it will extend this module beyond classification models to fit our face verification use case also.

Would love to hear your thoughts on this.

**Comment by gsarridis** [comment]
Great idea, Elmokhtar! Thanks for sharing it!

I've already started working on it, and I'll let you know once a new version of Facex is available.

**Comment by gsarridis** [comment]
Hi, 

I am pleased to share that the updated version of TC6 is now ready. I’ve tested it locally, and it works as expected for face verification models.

I've opened a pull request, so @maniospas, please review it when you can. 
Also, Elmokhtar, make sure you're using the latest version of facextool.

The relevant test example to run is `python tests/test_tc6_facex_fv.py`.

Please note that I couldn't upload the model’s state dict here due to its large size. You can download it from [here](https://drive.google.com/file/d/1Xa7XB9yrkiwxJ57vS-rg4AW1pONL4-Vt/view?usp=sharing). It’s the same model I sent you before, but this file includes only the state dict, with all irrelevant info removed to ensure proper loading in mammoth-commons.

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
H Iannis, 
Thank you for the nice integration of faceverif in facex. 
Can you udpate facextool ? I have the impression you didn't push your changes ?

**Comment by gsarridis** [comment]
Hi Elmokhtar, 

The updated version is the 0.1.11. You can get it directly from pypi ([link](https://pypi.org/project/facextool/)). 

If you prefer using facextool from github, I have just pushed the updated version there as well.

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
thank you ! (sorry I forget its on pip also)

**Comment by elmokhtar-mohamedmoussa-idnow** [comment]
its running greatly now with the examples data and model you provided ! thanks a lot for your help. I also see that you fixed the issue of the multiple popping plots.
I will close the issue now, the next step for me is to test on our inhouse data and model. I will get back to you If I have questions.
