### ISSUE TITLE
cannot opt for a model loader through the demonstrator

### ISSUE THREAD

**Issue by gsarridis** [mammoth-eu/mammoth-commons#19]
Clicking on "Choose a model loader" doesn't show any option.

![image](https://github.com/user-attachments/assets/e1262748-c42e-4a6c-96ab-2d60f2003fd7)

**Comment by maniospas** [comment]
Is your selected data loader perhaps `data_image_pairs` ? I think I was unsure which loaders it could be paired with when I was creating the demonstrator. Is `model_torch` compatible? 
(Linking is hand-wired in the demonstrator right now because it is yet undefined how the main toolkit will handle compatibility checks and I don't want to accidentally hamper some course of action.) 

If this is indeed compatible edit `demonstrator/backend/loaders.py` (or tell me to do this myself if my explanation makes no sense) by replacing:

```python
register(model_loaders, model_torch, compatible=[data_images])
```

with

```python
register(model_loaders, model_torch, compatible=[data_images, data_image_pairs])
```

P.S. If you can, please test the rest of image modules too, and check their descriptions and that info that appears when hovering over field names (you can edit them by editing the module docstring).

**Comment by gsarridis** [comment]
thanks Manie, I fixed the bug and created a pull request. 
I mark this issue as solved.
