### ISSUE TITLE
integration test working in my local system but failing here

### ISSUE THREAD

**Issue by arjunroyihrpa** [mammoth-eu/mammoth-commons#42]
Hi Manios,
I am struggling to understand why in my local system the integration test passes but in git it is failing. I literally cloned the latest mammoth-commons library and tested my changes, everything is working (see screenshot), however where it is going wrong when I am trying to push in the main git repo is something I am not getting.

Can you have look at it?

Best, 
Arjun

![Screenshot 2024-11-30 at 19 20 43](https://github.com/user-attachments/assets/04ff65db-5212-464f-bb40-c7c5ef7031fd)
![Screenshot 2024-11-30 at 19 21 44](https://github.com/user-attachments/assets/2c0419e5-0aef-4a91-b182-2382ec3462ca)

**Comment by maniospas** [comment]
Hi, this was probably an issue of the uploading for tc4b. For tc4a the issue was that Python had different arguments than what was being loaded (in your fork, the ensemble had a "sensiitve" argument but "sensitives" was being read). I merged your fork and fixed this as of commit [bd3dece](https://github.com/mammoth-eu/mammoth-commons/commit/bd3dece775b7f123fb4158653590ba8b98902712) .
